// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvEu0OzBf2MwlWmfhDQ6qlfNEYHHSPaOU',
    appId: '1:290571681787:web:d9f0b29a0b1bb5c838155e',
    messagingSenderId: '290571681787',
    projectId: 'studentfeedback-52c35',

    authDomain: 'studentfeedback-52c35.firebaseapp.com',
    storageBucket: 'studentfeedback-52c35.appspot.com',
    measurementId: 'G-04KMRFK38J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6k7XqjNbgphWuowWll0_ATWCJ5xL87Q',
    appId: '1:290571681787:android:e6242083729c5c4a38155e',
    messagingSenderId: '290571681787',
    projectId: 'studentfeedback-52c35',
    storageBucket: 'studentfeedback-52c35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUV2whzFudGXILGO7MJn7bGLtcGQrd1A',
    appId: '1:290571681787:ios:716427cc1fba7e1438155e',
    messagingSenderId: '290571681787',
    projectId: 'studentfeedback-52c35',
    storageBucket: 'studentfeedback-52c35.appspot.com',
    iosClientId: '290571681787-4ctknb6aj1spkmg9b4adk1rsvut9emfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentfeedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhUV2whzFudGXILGO7MJn7bGLtcGQrd1A',
    appId: '1:290571681787:ios:0b264c166543803138155e',
    messagingSenderId: '290571681787',
    projectId: 'studentfeedback-52c35',
    storageBucket: 'studentfeedback-52c35.appspot.com',
    iosClientId: '290571681787-eehgk5kbpnm9kv3dsq38esogdeaocmf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentfeedback.RunnerTests',
  );
}
